### ISSUE TITLE
Break website

### ISSUE THREAD

**Issue by ryanchansf** [hack4impact-calpoly/ecologistics-web-scraper#120]
Time to break the website! Now that we're nearing the end of the project, let's find some bugs that might need addressing before handoff. Go through the website and take note of any bugs that appear in the regular workflow throughout the site. Keep in mind that not everything is quite put together yet, so use your discretion for what you want to note down. 

Requirements:

- [x] Thoroughly test the whole website's functionality, including auth flow (login/logout, signup, etc.)
- [x] Check out logs to the console for uncaught errors
- [x] List found bugs in the comments (BONUS: potential solutions to some bugs too!)

**Comment by eewalia12** [comment]
List of potential issues:

1. When filtering the projects table, the search bar displays variables in camel case (i.e County File Number appears as countyFileNumber in the search bar). Not sure if this needs to be fixed but it is something that I noticed. This can be fixed by modifying the 'placeholder' attribute in line 145 of proposalTable.tsx.
2. Creating an account immediately sends the user to the login tab. It could be useful to automatically log the user in, or display a "user created"/confirmation to make it less confusing.
3. Logging in causes the following error message to be logged to the console: "Cannot update a component (`Router`) while rendering a different component (`LoginPage`). To locate the bad setState() call inside `LoginPage`"
