### ISSUE TITLE
Research mocking HTTP requests

### ISSUE THREAD

**Issue by oli-lane** [hack4impact-calpoly/ecologistics-web-scraper#56]
When we test our web scraping functions, we don't want to have to make requests to the actual live websites every time, so instead we'll **mock** the requests using the `unittest.mock` module. For this task, research how to write unit tests for a web scraping function using `unittest.mock` (and probably `patch`).

Requirements:
- [ ] Research commented beneath this issue
- [ ] Research contains step by step pseudocode for making a test case for (issue #48)

**Comment by sophiapeckner** [comment]
My research so far: [](https://docs.google.com/document/d/162UgEe1AMJfNqOC6ZWN2LasWu_9yaO-afuJsi-nPGI8/)

Will update the document with "Scraping meeting links layer 1" pseudocode when that code is ready so that way I can see what dependencies are at play. I believe requests will be used, which is in the example listed on the doc.
